console.log("hello world");

let box = "bottle";
console.log(box);

box = "phone";
console.log(box);

box = "wire";
console.log(box);

let city;

city = "Metu";

console.log("Metu");

city = "washington DC";

console.log("washington DC");

let speed = 50;
if (speed<30) {
    console.log ("no ticket");
}
else if (speed<=40) {
    console.log("50 dolar fine")
}
    else {
        console.log ("100 dolar fine")
    }

   let pro = prompt("well come to my page")

  let con;
   con = confirm("Hey buddy,wanna back")
   console.log(con)

   let al; 
   al = alert ("Hey yonas what the hek are you doing")
  console.log (al)
  
      
  
